id: PC2CD8332
initial_creation_type: ocr
source_metadata:
  volumes:
    cccf3ee3f6bc4e418e980dee70ccb10e:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: དགེ་འདུན་རྗེས་སུ་དྲན་པའི་བཤད་པ།
      total_pages: 1498
      volume_number: 65
