id: D735B49AB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:06:25+00:00'
last_modified: '2022-05-27T15:56:01.068302+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    9bdd:
      image_group_id: I1PD95910
      title: དགེ་འདུན་རྗེས་སུ་དྲན་པའི་བཤད་པ།
      total_pages: 1498
      order: 65
      base_file: 9bdd.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
